services:
  app:
    build: .
    container_name: dream-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shopping_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}

  postgres:
    image: postgres:15
    platform: linux/amd64
    container_name: dream-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: shopping_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123

